---
- hosts: webapp

  handlers:
    - name: 'reload webserver'
      become: yes
      command: /opt/webcorp/run-webcorp.sh kill -s HUP webapp-http

  tasks:
    - include_role:
        name: icarus
      vars:
        icarus_project_path: "{{ base_path }}/simplissima"
        icarus_release_name: "{{ gitlab_ci_commit_id | mandatory }}"
        icarus_sync_folders:
          - "{{ playbook_dir }}/../public"
        icarus_create_vhosts: 'yes'
        icarus_vhosts_template: "{{ playbook_dir }}/template/nginx.conf.j2"
        icarus_vhosts_filename: simplissima.conf
        icarus_vhosts_path: "{{ front_vhost_path }}"
